In [37]:
import pandas as pd
import numpy as np
import requests
from pandas.io.json import json_normalize
from flatten_json import flatten
from datetime import date

# OpenAQ API Conection

## List Countries

In [2]:
url = "https://api.openaq.org/v1/countries"

response = requests.get(url)
response

In [3]:
response.json()
# response.text
response.json()['results']

[{'code': 'AD',
  'count': 117680,
  'locations': 3,
  'cities': 2,
  'name': 'Andorra'},
 {'code': 'AE',
  'count': 76429,
  'locations': 4,
  'cities': 3,
  'name': 'United Arab Emirates'},
 {'code': 'AF',
  'count': 7172,
  'locations': 2,
  'cities': 2,
  'name': 'Afghanistan'},
 {'code': 'AG',
  'count': 1,
  'locations': 1,
  'cities': 1,
  'name': 'Antigua and Barbuda'},
 {'code': 'AR',
  'count': 14976,
  'locations': 4,
  'cities': 1,
  'name': 'Argentina'},
 {'code': 'AT',
  'count': 1701794,
  'locations': 541,
  'cities': 25,
  'name': 'Austria'},
 {'code': 'AU',
  'count': 6847982,
  'locations': 168,
  'cities': 53,
  'name': 'Australia'},
 {'code': 'BA',
  'count': 1086861,
  'locations': 22,
  'cities': 10,
  'name': 'Bosnia and Herzegovina'},
 {'code': 'BD',
  'count': 33744,
  'locations': 2,
  'cities': 1,
  'name': 'Bangladesh'},
 {'code': 'BE',
  'count': 1804382,
  'locations': 198,
  'cities': 14,
  'name': 'Belgium'},
 {'code': 'BG',
  'count': 3712,
  'locations': 1,
  'cities': 1,
  'name': 'Bulgaria'},
 {'code': 'BH',
  'count': 47382,
  'locations': 1,
  'cities': 1,
  'name': 'Bahrain'},
 {'code': 'BK', 'count': 3714, 'locations': 1, 'cities': 1},
 {'code': 'BM', 'count': 4779, 'locations': 1, 'cities': 1, 'name': 'Bermuda'},
 {'code': 'BR',
  'count': 304267,
  'locations': 61,
  'cities': 31,
  'name': 'Brazil'},
 {'code': 'CA',
  'count': 6320605,
  'locations': 213,
  'cities': 12,
  'name': 'Canada'},
 {'code': 'CE', 'count': 6361, 'locations': 1, 'cities': 1},
 {'code': 'CH',
  'count': 1558673,
  'locations': 30,
  'cities': 15,
  'name': 'Switzerland'},
 {'code': 'CI',
  'count': 445,
  'locations': 1,
  'cities': 1,
  'name': "Côte d'Ivoire"},
 {'code': 'CL',
  'count': 8120897,
  'locations': 240,
  'cities': 163,
  'name': 'Chile'},
 {'code': 'CN',
  'count': 101757058,
  'locations': 1724,
  'cities': 387,
  'name': 'China'},
 {'code': 'CO',
  'count': 662319,
  'locations': 34,
  'cities': 12,
  'name': 'Colombia'},
 {'code': 'CR',
  'count': 2924,
  'locations': 1,
  'cities': 1,
  'name': 'Costa Rica'},
 {'code': 'CS', 'count': 3445, 'locations': 2, 'cities': 1},
 {'code': 'CW',
  'count': 22795,
  'locations': 1,
  'cities': 1,
  'name': 'Curaçao'},
 {'code': 'CZ',
  'count': 6152067,
  'locations': 200,
  'cities': 15,
  'name': 'Czech Republic'},
 {'code': 'DE',
  'count': 12125080,
  'locations': 1086,
  'cities': 36,
  'name': 'Germany'},
 {'code': 'DK',
  'count': 587951,
  'locations': 25,
  'cities': 7,
  'name': 'Denmark'},
 {'code': 'DZ', 'count': 6951, 'locations': 1, 'cities': 1, 'name': 'Algeria'},
 {'code': 'ES',
  'count': 23838550,
  'locations': 1235,
  'cities': 115,
  'name': 'Spain'},
 {'code': 'ET',
  'count': 59211,
  'locations': 3,
  'cities': 2,
  'name': 'Ethiopia'},
 {'code': 'FI',
  'count': 2034356,
  'locations': 119,
  'cities': 35,
  'name': 'Finland'},
 {'code': 'FR',
  'count': 25439285,
  'locations': 1504,
  'cities': 135,
  'name': 'France'},
 {'code': 'GB',
  'count': 11164074,
  'locations': 162,
  'cities': 112,
  'name': 'United Kingdom'},
 {'code': 'GH', 'count': 1595, 'locations': 11, 'cities': 1, 'name': 'Ghana'},
 {'code': 'GI',
  'count': 40842,
  'locations': 6,
  'cities': 2,
  'name': 'Gibraltar'},
 {'code': 'GT',
  'count': 7416,
  'locations': 2,
  'cities': 2,
  'name': 'Guatemala'},
 {'code': 'HK',
  'count': 1564117,
  'locations': 16,
  'cities': 9,
  'name': 'Hong Kong'},
 {'code': 'HR',
  'count': 914122,
  'locations': 50,
  'cities': 17,
  'name': 'Croatia'},
 {'code': 'HU',
  'count': 2178747,
  'locations': 50,
  'cities': 14,
  'name': 'Hungary'},
 {'code': 'ID',
  'count': 79538,
  'locations': 5,
  'cities': 3,
  'name': 'Indonesia'},
 {'code': 'IE',
  'count': 503818,
  'locations': 38,
  'cities': 16,
  'name': 'Ireland'},
 {'code': 'IL',
  'count': 173130367,
  'locations': 2041,
  'cities': 14,
  'name': 'Israel'},
 {'code': 'IN',
  'count': 29646469,
  'locations': 455,
  'cities': 234,
  'name': 'India'},
 {'code': 'IQ', 'count': 9226, 'locations': 1, 'cities': 1, 'name': 'Iraq'},
 {'code': 'IS',
  'count': 28238,
  'locations': 15,
  'cities': 8,
  'name': 'Iceland'},
 {'code': 'IT',
  'count': 3894825,
  'locations': 104,
  'cities': 45,
  'name': 'Italy'},
 {'code': 'IZ', 'count': 2547, 'locations': 1, 'cities': 1},
 {'code': 'JO', 'count': 7247, 'locations': 2, 'cities': 2, 'name': 'Jordan'},
 {'code': 'KE', 'count': 2842, 'locations': 2, 'cities': 1, 'name': 'Kenya'},
 {'code': 'KG',
  'count': 12957,
  'locations': 2,
  'cities': 2,
  'name': 'Kyrgyzstan'},
 {'code': 'KU', 'count': 3565, 'locations': 1, 'cities': 1},
 {'code': 'KV', 'count': 3718, 'locations': 1, 'cities': 1},
 {'code': 'KW', 'count': 24510, 'locations': 1, 'cities': 1, 'name': 'Kuwait'},
 {'code': 'KZ',
  'count': 12237,
  'locations': 1,
  'cities': 1,
  'name': 'Kazakhstan'},
 {'code': 'LA',
  'count': 10281,
  'locations': 2,
  'cities': 2,
  'name': "Lao People's Democratic Republic"},
 {'code': 'LK',
  'count': 19151,
  'locations': 1,
  'cities': 1,
  'name': 'Sri Lanka'},
 {'code': 'LT',
  'count': 443306,
  'locations': 17,
  'cities': 8,
  'name': 'Lithuania'},
 {'code': 'LU',
  'count': 461451,
  'locations': 7,
  'cities': 3,
  'name': 'Luxembourg'},
 {'code': 'LV',
  'count': 196759,
  'locations': 4,
  'cities': 4,
  'name': 'Latvia'},
 {'code': 'MG',
  'count': 3318,
  'locations': 1,
  'cities': 1,
  'name': 'Madagascar'},
 {'code': 'MK',
  'count': 1271891,
  'locations': 45,
  'cities': 16,
  'name': 'Macedonia, the Former Yugoslav Republic of'},
 {'code': 'ML', 'count': 397, 'locations': 1, 'cities': 1, 'name': 'Mali'},
 {'code': 'MM',
  'count': 10179,
  'locations': 2,
  'cities': 2,
  'name': 'Myanmar'},
 {'code': 'MN',
  'count': 2832541,
  'locations': 44,
  'cities': 25,
  'name': 'Mongolia'},
 {'code': 'MT', 'count': 266353, 'locations': 4, 'cities': 4, 'name': 'Malta'},
 {'code': 'MX',
  'count': 3288553,
  'locations': 103,
  'cities': 5,
  'name': 'Mexico'},
 {'code': 'NG', 'count': 2541, 'locations': 1, 'cities': 1, 'name': 'Nigeria'},
 {'code': 'NL',
  'count': 8976194,
  'locations': 111,
  'cities': 67,
  'name': 'Netherlands'},
 {'code': 'NO',
  'count': 3621706,
  'locations': 88,
  'cities': 37,
  'name': 'Norway'},
 {'code': 'NP', 'count': 99447, 'locations': 6, 'cities': 2, 'name': 'Nepal'},
 {'code': 'PE', 'count': 732053, 'locations': 22, 'cities': 2, 'name': 'Peru'},
 {'code': 'PH',
  'count': 958,
  'locations': 1,
  'cities': 1,
  'name': 'Philippines'},
 {'code': 'PK',
  'count': 43878,
  'locations': 8,
  'cities': 5,
  'name': 'Pakistan'},
 {'code': 'PL',
  'count': 8378812,
  'locations': 233,
  'cities': 172,
  'name': 'Poland'},
 {'code': 'PT',
  'count': 3700345,
  'locations': 67,
  'cities': 16,
  'name': 'Portugal'},
 {'code': 'RS',
  'count': 252049,
  'locations': 6,
  'cities': 4,
  'name': 'Serbia'},
 {'code': 'RU',
  'count': 186861,
  'locations': 48,
  'cities': 1,
  'name': 'Russian Federation'},
 {'code': 'SA',
  'count': 7205,
  'locations': 2,
  'cities': 2,
  'name': 'Saudi Arabia'},
 {'code': 'SE',
  'count': 293247,
  'locations': 11,
  'cities': 3,
  'name': 'Sweden'},
 {'code': 'SG',
  'count': 1275,
  'locations': 1,
  'cities': 1,
  'name': 'Singapore'},
 {'code': 'SI',
  'count': 149926,
  'locations': 9,
  'cities': 9,
  'name': 'Slovenia'},
 {'code': 'SK',
  'count': 2488665,
  'locations': 38,
  'cities': 8,
  'name': 'Slovakia'},
 {'code': 'TH',
  'count': 5333430,
  'locations': 64,
  'cities': 29,
  'name': 'Thailand'},
 {'code': 'TI', 'count': 3727, 'locations': 1, 'cities': 1},
 {'code': 'TJ',
  'count': 3949,
  'locations': 1,
  'cities': 1,
  'name': 'Tajikistan'},
 {'code': 'TM',
  'count': 3947,
  'locations': 1,
  'cities': 1,
  'name': 'Turkmenistan'},
 {'code': 'TR',
  'count': 5640285,
  'locations': 159,
  'cities': 43,
  'name': 'Turkey'},
 {'code': 'TW',
  'count': 7584525,
  'locations': 144,
  'cities': 30,
  'name': 'Taiwan'},
 {'code': 'TX', 'count': 3585, 'locations': 1, 'cities': 1},
 {'code': 'UC', 'count': 1, 'locations': 1, 'cities': 1},
 {'code': 'UG', 'count': 27939, 'locations': 2, 'cities': 2, 'name': 'Uganda'},
 {'code': 'US',
  'count': 67729065,
  'locations': 2267,
  'cities': 790,
  'name': 'United States'},
 {'code': 'UZ',
  'count': 30672,
  'locations': 2,
  'cities': 2,
  'name': 'Uzbekistan'},
 {'code': 'VM', 'count': 2384, 'locations': 2, 'cities': 1},
 {'code': 'VN',
  'count': 73378,
  'locations': 5,
  'cities': 3,
  'name': 'Viet Nam'},
 {'code': 'XK',
  'count': 417423,
  'locations': 9,
  'cities': 8,
  'name': 'Kosovo'},
 {'code': 'ZA',
  'count': 239159,
  'locations': 3,
  'cities': 1,
  'name': 'South Africa'}]

In [4]:
# Convert to DF
data = pd.DataFrame(response.json()['results'])
data['name'].unique()
data.head()
# data.columns

   cities code   count  locations                  name
0       2   AD  117680          3               Andorra
1       3   AE   76429          4  United Arab Emirates
2       2   AF    7172          2           Afghanistan
3       1   AG       1          1   Antigua and Barbuda
4       1   AR   14976          4             Argentina

In [6]:
# Countries with the highest number of observations
data = pd.DataFrame(json_normalize(response.json()['results']))
data.sort_values(by='count', ascending=False).head(20)

    cities code      count  locations            name
42      14   IL  173130367       2041          Israel
20     387   CN  101757058       1724           China
92     790   US   67729065       2267   United States
43     234   IN   29646469        455           India
32     135   FR   25439285       1504          France
29     115   ES   23838550       1235           Spain
26      36   DE   12125080       1086         Germany
33     112   GB   11164074        162  United Kingdom
68      67   NL    8976194        111     Netherlands
74     172   PL    8378812        233          Poland
19     163   CL    8120897        240           Chile
88      30   TW    7584525        144          Taiwan
6       53   AU    6847982        168       Australia
15      12   CA    6320605        213          Canada
25      15   CZ    6152067        200  Czech Republic
87      43   TR    5640285        159          Turkey
83      29   TH    5333430         64        Thailand
46      45   IT    3894825        104           Italy
75      16   PT    3700345         67        Portugal
69      37   NO    3621706         88          Norway

## Listing cities

In [20]:
# Cities
url = "https://api.openaq.org/v1/cities"

response = requests.get(url)
response

In [21]:
response.json()

{'meta': {'name': 'openaq-api',
  'license': 'CC BY 4.0',
  'website': 'https://docs.openaq.org/',
  'page': 1,
  'limit': 100,
  'found': 2892},
 'results': [{'country': 'AD',
   'name': 'Escaldes-Engordany',
   'city': 'Escaldes-Engordany',
   'count': 109098,
   'locations': 2},
  {'country': 'AD',
   'name': 'unused',
   'city': 'unused',
   'count': 8582,
   'locations': 1},
  {'country': 'AE',
   'name': 'Abu Dhabi',
   'city': 'Abu Dhabi',
   'count': 34558,
   'locations': 1},
  {'country': 'AE',
   'name': 'Dubai',
   'city': 'Dubai',
   'count': 27617,
   'locations': 1},
  {'country': 'AE',
   'name': 'N/A',
   'city': 'N/A',
   'count': 14254,
   'locations': 2},
  {'country': 'AF',
   'name': 'Kabul',
   'city': 'Kabul',
   'count': 3949,
   'locations': 1},
  {'country': 'AF',
   'name': 'N/A',
   'city': 'N/A',
   'count': 3223,
   'locations': 1},
  {'country': 'AG', 'name': 'N/A', 'city': 'N/A', 'count': 1, 'locations': 1},
  {'country': 'AR',
   'name': 'Buenos Aires',
   'city': 'Buenos Aires',
   'count': 14976,
   'locations': 4},
  {'country': 'AT',
   'name': 'Amt der Burgenländischen Landesregierung',
   'city': 'Amt der Burgenländischen Landesregierung',
   'count': 471,
   'locations': 1},
  {'country': 'AT',
   'name': 'Amt der Burgenl�ndischen Landesregierung',
   'city': 'Amt der Burgenl�ndischen Landesregierung',
   'count': 35608,
   'locations': 3},
  {'country': 'AT',
   'name': 'Amt der Kärntner Landesregierung',
   'city': 'Amt der Kärntner Landesregierung',
   'count': 471,
   'locations': 1},
  {'country': 'AT',
   'name': 'Amt der K�rntner Landesregierung',
   'city': 'Amt der K�rntner Landesregierung',
   'count': 104663,
   'locations': 16},
  {'country': 'AT',
   'name': 'Amt der Niederösterreichischen Landesregierung',
   'city': 'Amt der Niederösterreichischen Landesregierung',
   'count': 1413,
   'locations': 3},
  {'country': 'AT',
   'name': 'Amt der Nieder�sterreichischen Landesregierung',
   'city': 'Amt der Nieder�sterreichischen Landesregierung',
   'count': 322499,
   'locations': 39},
  {'country': 'AT',
   'name': 'Amt der Oberösterreichischen Landesregierung',
   'city': 'Amt der Oberösterreichischen Landesregierung',
   'count': 2828,
   'locations': 6},
  {'country': 'AT',
   'name': 'Amt der Ober�sterreichischen Landesregierung',
   'city': 'Amt der Ober�sterreichischen Landesregierung',
   'count': 154329,
   'locations': 16},
  {'country': 'AT',
   'name': 'Amt der Salzburger Landesregierung',
   'city': 'Amt der Salzburger Landesregierung',
   'count': 94197,
   'locations': 12},
  {'country': 'AT',
   'name': 'Amt der Steiermärkischen Landesregierung',
   'city': 'Amt der Steiermärkischen Landesregierung',
   'count': 1891,
   'locations': 4},
  {'country': 'AT',
   'name': 'Amt der Steierm�rkischen Landesregierung',
   'city': 'Amt der Steierm�rkischen Landesregierung',
   'count': 320372,
   'locations': 41},
  {'country': 'AT',
   'name': 'Amt der Tiroler Landesregierung',
   'city': 'Amt der Tiroler Landesregierung',
   'count': 113161,
   'locations': 19},
  {'country': 'AT',
   'name': 'Austria',
   'city': 'Austria',
   'count': 121987,
   'locations': 174},
  {'country': 'AT',
   'name': 'Burgenland',
   'city': 'Burgenland',
   'count': 6779,
   'locations': 4},
  {'country': 'AT',
   'name': 'Gemeinde Wien, MA22 Umweltschutz',
   'city': 'Gemeinde Wien, MA22 Umweltschutz',
   'count': 130328,
   'locations': 21},
  {'country': 'AT',
   'name': 'Kärnten',
   'city': 'Kärnten',
   'count': 15255,
   'locations': 14},
  {'country': 'AT',
   'name': 'Niederösterreich',
   'city': 'Niederösterreich',
   'count': 43273,
   'locations': 40},
  {'country': 'AT',
   'name': 'Oberösterreich',
   'city': 'Oberösterreich',
   'count': 26563,
   'locations': 16},
  {'country': 'AT',
   'name': 'Salzburg',
   'city': 'Salzburg',
   'count': 12046,
   'locations': 12},
  {'country': 'AT',
   'name': 'Steiermark',
   'city': 'Steiermark',
   'count': 38023,
   'locations': 38},
  {'country': 'AT',
   'name': 'Tirol',
   'city': 'Tirol',
   'count': 14332,
   'locations': 19},
  {'country': 'AT',
   'name': 'Umweltbundesamt',
   'city': 'Umweltbundesamt',
   'count': 81025,
   'locations': 8},
  {'country': 'AT',
   'name': 'Umweltinstitut des Landes Vorarlberg',
   'city': 'Umweltinstitut des Landes Vorarlberg',
   'count': 36108,
   'locations': 9},
  {'country': 'AT',
   'name': 'Vorarlberg',
   'city': 'Vorarlberg',
   'count': 4098,
   'locations': 8},
  {'country': 'AT',
   'name': 'Wien',
   'city': 'Wien',
   'count': 20074,
   'locations': 17},
  {'country': 'AU',
   'name': 'Adelaide',
   'city': 'Adelaide',
   'count': 55740,
   'locations': 9},
  {'country': 'AU',
   'name': 'Bairnsdale',
   'city': 'Bairnsdale',
   'count': 981,
   'locations': 1},
  {'country': 'AU',
   'name': 'Bairnsdale ',
   'city': 'Bairnsdale ',
   'count': 50,
   'locations': 1},
  {'country': 'AU',
   'name': 'Bright',
   'city': 'Bright',
   'count': 958,
   'locations': 1},
  {'country': 'AU',
   'name': 'Campbellfield',
   'city': 'Campbellfield',
   'count': 1200,
   'locations': 1},
  {'country': 'AU',
   'name': 'Canberra',
   'city': 'Canberra',
   'count': 33006,
   'locations': 3},
  {'country': 'AU',
   'name': 'Cann River',
   'city': 'Cann River',
   'count': 660,
   'locations': 1},
  {'country': 'AU',
   'name': 'Central Coast',
   'city': 'Central Coast',
   'count': 193762,
   'locations': 1},
  {'country': 'AU',
   'name': 'Central Queensland',
   'city': 'Central Queensland',
   'count': 43076,
   'locations': 4},
  {'country': 'AU',
   'name': 'Central Tablelands',
   'city': 'Central Tablelands',
   'count': 65594,
   'locations': 2},
  {'country': 'AU',
   'name': 'Churchill',
   'city': 'Churchill',
   'count': 1895,
   'locations': 1},
  {'country': 'AU',
   'name': 'Geelong',
   'city': 'Geelong',
   'count': 10708,
   'locations': 1},
  {'country': 'AU',
   'name': 'Gladstone',
   'city': 'Gladstone',
   'count': 558131,
   'locations': 8},
  {'country': 'AU',
   'name': 'Illawarra',
   'city': 'Illawarra',
   'count': 487842,
   'locations': 3},
  {'country': 'AU',
   'name': 'Lakes Entrance',
   'city': 'Lakes Entrance',
   'count': 404,
   'locations': 1},
  {'country': 'AU',
   'name': 'Lower Hunter',
   'city': 'Lower Hunter',
   'count': 488191,
   'locations': 3},
  {'country': 'AU',
   'name': 'Mackay',
   'city': 'Mackay',
   'count': 30102,
   'locations': 2},
  {'country': 'AU',
   'name': 'Mallacoota',
   'city': 'Mallacoota',
   'count': 706,
   'locations': 1},
  {'country': 'AU',
   'name': 'Marlo',
   'city': 'Marlo',
   'count': 604,
   'locations': 1},
  {'country': 'AU',
   'name': 'Melbourne',
   'city': 'Melbourne',
   'count': 53385,
   'locations': 11},
  {'country': 'AU',
   'name': 'Melton',
   'city': 'Melton',
   'count': 3790,
   'locations': 1},
  {'country': 'AU',
   'name': 'Moe',
   'city': 'Moe',
   'count': 2061,
   'locations': 1},
  {'country': 'AU',
   'name': 'Morwell',
   'city': 'Morwell',
   'count': 14221,
   'locations': 2},
  {'country': 'AU',
   'name': 'Mount Isa',
   'city': 'Mount Isa',
   'count': 11538,
   'locations': 2},
  {'country': 'AU',
   'name': 'Mt Isa',
   'city': 'Mt Isa',
   'count': 43106,
   'locations': 2},
  {'country': 'AU',
   'name': 'Newborough',
   'city': 'Newborough',
   'count': 1517,
   'locations': 1},
  {'country': 'AU',
   'name': 'Nicholson',
   'city': 'Nicholson',
   'count': 181,
   'locations': 1},
  {'country': 'AU',
   'name': 'Northern Tablelands',
   'city': 'Northern Tablelands',
   'count': 4436,
   'locations': 1},
  {'country': 'AU',
   'name': 'North-west Slopes',
   'city': 'North-west Slopes',
   'count': 75151,
   'locations': 3},
  {'country': 'AU',
   'name': 'Omeo',
   'city': 'Omeo',
   'count': 991,
   'locations': 1},
  {'country': 'AU',
   'name': 'Orbost',
   'city': 'Orbost',
   'count': 934,
   'locations': 1},
  {'country': 'AU',
   'name': 'Point Cook',
   'city': 'Point Cook',
   'count': 844,
   'locations': 1},
  {'country': 'AU',
   'name': 'Port Augusta',
   'city': 'Port Augusta',
   'count': 4814,
   'locations': 1},
  {'country': 'AU',
   'name': 'Port Pirie',
   'city': 'Port Pirie',
   'count': 4843,
   'locations': 1},
  {'country': 'AU',
   'name': 'Rosedale',
   'city': 'Rosedale',
   'count': 2070,
   'locations': 1},
  {'country': 'AU',
   'name': 'Sarsfield',
   'city': 'Sarsfield',
   'count': 482,
   'locations': 1},
  {'country': 'AU',
   'name': 'South East Queensland',
   'city': 'South East Queensland',
   'count': 958163,
   'locations': 15},
  {'country': 'AU',
   'name': 'Southern Tablelands',
   'city': 'Southern Tablelands',
   'count': 8660,
   'locations': 1},
  {'country': 'AU',
   'name': 'South West Queensland',
   'city': 'South West Queensland',
   'count': 171564,
   'locations': 5},
  {'country': 'AU',
   'name': 'South-west Slopes',
   'city': 'South-west Slopes',
   'count': 120274,
   'locations': 2},
  {'country': 'AU',
   'name': "Swift's Creek",
   'city': "Swift's Creek",
   'count': 1003,
   'locations': 1},
  {'country': 'AU',
   'name': 'Sydney East',
   'city': 'Sydney East',
   'count': 733652,
   'locations': 7},
  {'country': 'AU',
   'name': 'Sydney North-west',
   'city': 'Sydney North-west',
   'count': 514025,
   'locations': 6},
  {'country': 'AU',
   'name': 'Sydney South-west',
   'city': 'Sydney South-west',
   'count': 881257,
   'locations': 6},
  {'country': 'AU',
   'name': 'Tasmania Region',
   'city': 'Tasmania Region',
   'count': 876156,
   'locations': 34},
  {'country': 'AU',
   'name': 'Townsville',
   'city': 'Townsville',
   'count': 105821,
   'locations': 5},
  {'country': 'AU',
   'name': 'Traralgon',
   'city': 'Traralgon',
   'count': 11360,
   'locations': 1},
  {'country': 'AU',
   'name': 'Upper Hunter - Muswellbrook',
   'city': 'Upper Hunter - Muswellbrook',
   'count': 128782,
   'locations': 1},
  {'country': 'AU',
   'name': 'Upper Hunter - Singleton',
   'city': 'Upper Hunter - Singleton',
   'count': 129466,
   'locations': 1},
  {'country': 'AU',
   'name': 'Wangaratta',
   'city': 'Wangaratta',
   'count': 2052,
   'locations': 1},
  {'country': 'AU',
   'name': 'Whyalla',
   'city': 'Whyalla',
   'count': 4715,
   'locations': 3},
  {'country': 'AU',
   'name': 'Wodonga',
   'city': 'Wodonga',
   'count': 1001,
   'locations': 1},
  {'country': 'AU',
   'name': 'Yinnar',
   'city': 'Yinnar',
   'count': 2057,
   'locations': 1},
  {'country': 'BA',
   'name': 'Goražde',
   'city': 'Goražde',
   'count': 70797,
   'locations': 1},
  {'country': 'BA',
   'name': 'Ilijaš',
   'city': 'Ilijaš',
   'count': 2912,
   'locations': 1},
  {'country': 'BA',
   'name': 'Jajce',
   'city': 'Jajce',
   'count': 62562,
   'locations': 1},
  {'country': 'BA',
   'name': 'Kakanj',
   'city': 'Kakanj',
   'count': 5637,
   'locations': 1},
  {'country': 'BA',
   'name': 'Lukavac',
   'city': 'Lukavac',
   'count': 97267,
   'locations': 1},
  {'country': 'BA',
   'name': 'N/A',
   'city': 'N/A',
   'count': 16031,
   'locations': 1},
  {'country': 'BA',
   'name': 'Sarajevo',
   'city': 'Sarajevo',
   'count': 268121,
   'locations': 8},
  {'country': 'BA',
   'name': 'Tuzla',
   'city': 'Tuzla',
   'count': 249482,
   'locations': 3},
  {'country': 'BA',
   'name': 'Zenica',
   'city': 'Zenica',
   'count': 233517,
   'locations': 4},
  {'country': 'BA',
   'name': 'Živinice',
   'city': 'Živinice',
   'count': 80535,
   'locations': 1},
  {'country': 'BD',
   'name': 'Dhaka',
   'city': 'Dhaka',
   'count': 33744,
   'locations': 2},
  {'country': 'BE',
   'name': 'Antwerpen',
   'city': 'Antwerpen',
   'count': 145950,
   'locations': 24},
  {'country': 'BE',
   'name': 'Brabant wallon',
   'city': 'Brabant wallon',
   'count': 19188,
   'locations': 1}]}

In [22]:
cities = pd.DataFrame(json_normalize(response.json()['results']))
cities.sort_values(by='count', ascending=False)

,city,count,country,locations,name
70,South East Queensland,958163,AU,15,South East Queensland
77,Sydney South-west,881257,AU,6,Sydney South-west
78,Tasmania Region,876156,AU,34,Tasmania Region
75,Sydney East,733652,AU,7,Sydney East
46,Gladstone,558131,AU,8,Gladstone
76,Sydney North-west,514025,AU,6,Sydney North-west
49,Lower Hunter,488191,AU,3,Lower Hunter
47,Illawarra,487842,AU,3,Illawarra
14,Amt der Nieder�sterreichischen Landesregierung,322499,AT,39,Amt der Nieder�sterreichischen Landesregierung
19,Amt der Steierm�rkischen Landesregierung,320372,AT,41,Amt der Steierm�rkischen Landesregierung
93,Sarajevo,268121,BA,8,Sarajevo
94,Tuzla,249482,BA,3,Tuzla
95,Zenica,233517,BA,4,Zenica
41,Central Coast,193762,AU,1,Central Coast
72,South West Queensland,171564,AU,5,South West Queensland
16,Amt der Ober�sterreichischen Landesregierung,154329,AT,16,Amt der Ober�sterreichischen Landesregierung
98,Antwerpen,145950,BE,24,Antwerpen
23,"Gemeinde Wien, MA22 Umweltschutz",130328,AT,21,"Gemeinde Wien, MA22 Umweltschutz"
82,Upper Hunter - Singleton,129466,AU,1,Upper Hunter - Singleton
81,Upper Hunter - Muswellbrook,128782,AU,1,Upper Hunter - Muswellbrook
21,Austria,121987,AT,174,Austria
73,South-west Slopes,120274,AU,2,South-west Slopes
20,Amt der Tiroler Landesregierung,113161,AT,19,Amt der Tiroler Landesregierung
0,Escaldes-Engordany,109098,AD,2,Escaldes-Engordany
79,Townsville,105821,AU,5,Townsville
12,Amt der K�rntner Landesregierung,104663,AT,16,Amt der K�rntner Landesregierung
91,Lukavac,97267,BA,1,Lukavac
17,Amt der Salzburger Landesregierung,94197,AT,12,Amt der Salzburger Landesregierung
30,Umweltbundesamt,81025,AT,8,Umweltbundesamt
96,Živinice,80535,BA,1,Živinice
...,...,...,...,...,...
54,Melton,3790,AU,1,Melton
6,N/A,3223,AF,1,N/A
88,Ilijaš,2912,BA,1,Ilijaš
15,Amt der Oberösterreichischen Landesregierung,2828,AT,6,Amt der Oberösterreichischen Landesregierung
68,Rosedale,2070,AU,1,Rosedale
55,Moe,2061,AU,1,Moe
86,Yinnar,2057,AU,1,Yinnar
83,Wangaratta,2052,AU,1,Wangaratta
44,Churchill,1895,AU,1,Churchill
18,Amt der Steiermärkischen Landesregierung,1891,AT,4,Amt der Steiermärkischen Landesregierung
59,Newborough,1517,AU,1,Newborough
13,Amt der Niederösterreichischen Landesregierung,1413,AT,3,Amt der Niederösterreichischen Landesregierung
38,Campbellfield,1200,AU,1,Campbellfield
74,Swift's Creek,1003,AU,1,Swift's Creek
85,Wodonga,1001,AU,1,Wodonga
63,Omeo,991,AU,1,Omeo
35,Bairnsdale,981,AU,1,Bairnsdale
37,Bright,958,AU,1,Bright
64,Orbost,934,AU,1,Orbost
65,Point Cook,844,AU,1,Point Cook
51,Mallacoota,706,AU,1,Mallacoota
40,Cann River,660,AU,1,Cann River
52,Marlo,604,AU,1,Marlo
69,Sarsfield,482,AU,1,Sarsfield
9,Amt der Burgenländischen Landesregierung,471,AT,1,Amt der Burgenländischen Landesregierung
11,Amt der Kärntner Landesregierung,471,AT,1,Amt der Kärntner Landesregierung
48,Lakes Entrance,404,AU,1,Lakes Entrance
60,Nicholson,181,AU,1,Nicholson
36,Bairnsdale,50,AU,1,Bairnsdale
7,N/A,1,AG,1,N/A

## Requesting the latest data.

In [6]:
# criar outro df pra measurements
url = "https://api.openaq.org/v1/latest?country=US"

response = requests.get(url)
response
response.json()

{'meta': {'name': 'openaq-api',
  'license': 'CC BY 4.0',
  'website': 'https://docs.openaq.org/',
  'page': 1,
  'limit': 100,
  'found': 2179},
 'results': [{'location': '1001',
   'city': 'CA8 - ARB',
   'country': 'US',
   'distance': 8648898.161045589,
   'measurements': [{'parameter': 'pm25',
     'value': 13.9,
     'lastUpdated': '2020-03-09T15:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.684364, 'longitude': -120.98818}},
  {'location': '1008',
   'city': 'CA8 - ARB',
   'country': 'US',
   'distance': 8648331.782792693,
   'measurements': [{'parameter': 'pm25',
     'value': -4.2,
     'lastUpdated': '2020-03-09T17:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.67386, 'longitude': -120.94338}},
  {'location': '16th and Whitmore',
   'city': 'Omaha-Council Bluffs',
   'country': 'US',
   'distance': 7317289.4981282065,
   'measurements': [{'parameter': 'o3',
     'value': 0.016,
     'lastUpdated': '2017-11-01T11:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'so2',
     'value': 0,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.32247, 'longitude': -95.93799}},
  {'location': '1NL Navajo Lake',
   'city': 'Farmington',
   'country': 'US',
   'distance': 8289568.688757036,
   'measurements': [{'parameter': 'o3',
     'value': 0.024,
     'lastUpdated': '2017-01-13T15:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 36.8097, 'longitude': -107.6517}},
  {'location': '22nd Street & Craycr',
   'city': 'Tucson',
   'country': 'US',
   'distance': 8880825.353075182,
   'measurements': [{'parameter': 'o3',
     'value': 0.054,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 32.205, 'longitude': -110.8772}},
  {'location': '24th & O',
   'city': 'Omaha-Council Bluffs',
   'country': 'US',
   'distance': 7328058.090918123,
   'measurements': [{'parameter': 'o3',
     'value': 0.012,
     'lastUpdated': '2017-11-01T11:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.208084, 'longitude': -95.94744}},
  {'location': '2912 Coffey',
   'city': 'Omaha-Council Bluffs',
   'country': 'US',
   'distance': 7335220.451681372,
   'measurements': [{'parameter': 'pm25',
     'value': 2,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.133316, 'longitude': -95.95608}},
  {'location': '2LL Los Lunas',
   'city': 'Albuquerque',
   'country': 'US',
   'distance': 8439227.634263288,
   'measurements': [{'parameter': 'o3',
     'value': 0.055,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 34.8147, 'longitude': -106.7397}},
  {'location': '46th and Farnam',
   'city': 'Omaha-Council Bluffs',
   'country': 'US',
   'distance': 7325406.147325607,
   'measurements': [{'parameter': 'pm10',
     'value': 0,
     'lastUpdated': '2018-04-25T04:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.257317, 'longitude': -95.98383}},
  {'location': '5511 39TH STREET EAS',
   'city': 'Sarasota-Bradenton-Venice',
   'country': 'US',
   'distance': 7829309.7824333655,
   'measurements': [{'parameter': 'o3',
     'value': 0.013,
     'lastUpdated': '2017-11-07T02:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 27.4494, 'longitude': -82.5219}},
  {'location': '60 Near Road',
   'city': 'SAN BERNARDINO',
   'country': 'US',
   'distance': 8987790.972990196,
   'measurements': [{'parameter': 'pm25',
     'value': 51,
     'lastUpdated': '2018-06-08T16:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'no2',
     'value': 0.03,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 34.0309, 'longitude': -117.6174}},
  {'location': '6th District',
   'city': 'Cleveland-Elyria-Mentor',
   'country': 'US',
   'distance': 6550312.190019143,
   'measurements': [{'parameter': 'o3',
     'value': 0.032,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.55523, 'longitude': -81.57526}},
  {'location': '7004',
   'city': 'ARCHULETA',
   'country': 'US',
   'distance': 8233678.593376018,
   'measurements': [{'parameter': 'o3',
     'value': 0.042,
     'lastUpdated': '2020-02-10T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'so2',
     'value': 0.002,
     'lastUpdated': '2020-02-10T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'no2',
     'value': 0.003,
     'lastUpdated': '2020-02-10T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 37.20586, 'longitude': -107.25412}},
  {'location': '710 Near Road',
   'city': 'LOS ANGELES',
   'country': 'US',
   'distance': 9028327.960355323,
   'measurements': [{'parameter': 'no2',
     'value': 0.03,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 16.5,
     'lastUpdated': '2018-06-08T12:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 33.85966, 'longitude': -118.20071}},
  {'location': '77th and Dodge',
   'city': 'Omaha-Council Bluffs',
   'country': 'US',
   'distance': 7327704.701870088,
   'measurements': [{'parameter': 'co',
     'value': 0.29,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.25948, 'longitude': -96.03471}},
  {'location': '7E Deming Airport',
   'city': 'Deming',
   'country': 'US',
   'distance': 8731130.783172999,
   'measurements': [{'parameter': 'pm10',
     'value': 12,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 32.2558, 'longitude': -107.7228}},
  {'location': 'A Street',
   'city': 'FAIRBANKS NORTH STAR',
   'country': 'US',
   'distance': 6515930.781871644,
   'measurements': [{'parameter': 'pm25',
     'value': 10,
     'lastUpdated': '2019-11-09T14:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 2,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 64.84593, 'longitude': -147.69328}},
  {'location': 'ADEQ-DSR',
   'city': 'Little Rock-North Little Rock',
   'country': 'US',
   'distance': 7731975.612364057,
   'measurements': [{'parameter': 'pm25',
     'value': 3.8,
     'lastUpdated': '2020-03-30T18:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 34.6811, 'longitude': -92.3283}},
  {'location': 'AIR LAB',
   'city': 'Knoxville',
   'country': 'US',
   'distance': 7157596.134833732,
   'measurements': [{'parameter': 'pm25',
     'value': 5.3,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 35.9803, 'longitude': -83.9306}},
  {'location': 'AJ Maintenance Yard',
   'city': 'Phoenix-Mesa-Scottsdale',
   'country': 'US',
   'distance': 8789918.309850113,
   'measurements': [{'parameter': 'o3',
     'value': 0.059,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 33.4206, 'longitude': -111.5033}},
  {'location': 'ALBA',
   'city': 'Joplin',
   'country': 'US',
   'distance': 7610219.540200055,
   'measurements': [{'parameter': 'o3',
     'value': 0.042,
     'lastUpdated': '2020-03-30T21:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 37.2385, 'longitude': -94.42468}},
  {'location': 'ALBNY',
   'city': 'Albany-Schenectady-Troy',
   'country': 'US',
   'distance': 6024704.674799274,
   'measurements': [{'parameter': 'pm25',
     'value': 9.5,
     'lastUpdated': '2018-02-27T11:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 42.6425, 'longitude': -73.7547}},
  {'location': 'ALLE',
   'city': 'Allentown-Bethlehem-Easton',
   'country': 'US',
   'distance': 6284750.124186543,
   'measurements': [{'parameter': 'o3',
     'value': 0.033,
     'lastUpdated': '2018-10-13T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 0.9,
     'lastUpdated': '2018-10-05T15:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 40.6119, 'longitude': -75.4325}},
  {'location': 'ALLEN PARK',
   'city': 'Detroit-Warren-Livonia',
   'country': 'US',
   'distance': 6582501.065232539,
   'measurements': [{'parameter': 'co',
     'value': 0,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 4.2,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'so2',
     'value': 0.001,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.033,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 42.2283, 'longitude': -83.2092}},
  {'location': 'ALSIP',
   'city': 'Chicago-Naperville-Joliet',
   'country': 'US',
   'distance': 6870315.081425183,
   'measurements': [{'parameter': 'pm25',
     'value': 0.2,
     'lastUpdated': '2020-03-29T11:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.041,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 41.6708, 'longitude': -87.7325}},
  {'location': 'ALTO',
   'city': 'Altoona',
   'country': 'US',
   'distance': 6460305.562409385,
   'measurements': [{'parameter': 'pm25',
     'value': 8.1,
     'lastUpdated': '2018-04-18T18:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.037,
     'lastUpdated': '2018-04-18T18:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 40.515, 'longitude': -78.3889}},
  {'location': 'ALTON',
   'city': 'St. Louis',
   'country': 'US',
   'distance': 7240076.751157881,
   'measurements': [{'parameter': 'o3',
     'value': 0.02,
     'lastUpdated': '2019-11-06T15:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.8903, 'longitude': -90.1481}},
  {'location': 'APOLLO BEACH',
   'city': 'HILLSBOROUGH',
   'country': 'US',
   'distance': 7793837.33566706,
   'measurements': [{'parameter': 'pm25',
     'value': 12.4,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'so2',
     'value': 0.001,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 27.779713, 'longitude': -82.41984}},
  {'location': 'APPLETON AAL',
   'city': 'Appleton',
   'country': 'US',
   'distance': 6678007.769781301,
   'measurements': [{'parameter': 'pm25',
     'value': 2.5,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.045,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 44.3069, 'longitude': -88.3956}},
  {'location': 'ARB OER',
   'city': 'CA8 - ARB',
   'country': 'US',
   'distance': 8678884.787514225,
   'measurements': [{'parameter': 'pm25',
     'value': -4,
     'lastUpdated': '2016-08-08T16:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.568504, 'longitude': -121.493256}},
  {'location': 'AREN',
   'city': 'Gettysburg',
   'country': 'US',
   'distance': 6448362.207000937,
   'measurements': [{'parameter': 'pm25',
     'value': 7.4,
     'lastUpdated': '2018-04-18T18:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.046,
     'lastUpdated': '2018-04-18T18:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 39.9233, 'longitude': -77.3081}},
  {'location': 'ARNOLD',
   'city': 'St. Louis',
   'country': 'US',
   'distance': 7292342.313764914,
   'measurements': [{'parameter': 'o3',
     'value': 0.003,
     'lastUpdated': '2019-11-06T12:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm10',
     'value': 19,
     'lastUpdated': '2019-11-15T13:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 13,
     'lastUpdated': '2019-11-15T13:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.44858, 'longitude': -90.39844}},
  {'location': 'ARNOLD WEST',
   'city': 'St. Louis',
   'country': 'US',
   'distance': 7292342.313764914,
   'measurements': [{'parameter': 'pm10',
     'value': 6,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 6.6,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.048,
     'lastUpdated': '2020-03-30T21:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.44858, 'longitude': -90.39844}},
  {'location': 'ASHBURN',
   'city': 'Washington-Arlington-Alexandria',
   'country': 'US',
   'distance': 6533564.542167597,
   'measurements': [{'parameter': 'o3',
     'value': 0.05,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'no2',
     'value': 0.002,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 39.0244, 'longitude': -77.49}},
  {'location': 'ATHENS',
   'city': 'Athens',
   'country': 'US',
   'distance': 7241211.949024892,
   'measurements': [{'parameter': 'pm25',
     'value': 4,
     'lastUpdated': '2020-03-26T15:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 35.4511, 'longitude': -84.5992}},
  {'location': 'AURORA HILLS',
   'city': 'Washington-Arlington-Alexandria',
   'country': 'US',
   'distance': 6522702.4777639955,
   'measurements': [{'parameter': 'no2',
     'value': 0.002,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'o3',
     'value': 0.05,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'co',
     'value': 0.2,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'ppm',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 38.8594, 'longitude': -77.0589}},
  {'location': 'Aberdeen',
   'city': 'BROWN',
   'country': 'US',
   'distance': 7065432.790527657,
   'measurements': [{'parameter': 'pm10',
     'value': 20,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 1.8,
     'lastUpdated': '2020-03-30T20:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 45.468597, 'longitude': -98.494064}},
  {'location': 'Aberdeen Bus Stop',
   'city': 'BROWN',
   'country': 'US',
   'distance': 7065432.790527657,
   'measurements': [{'parameter': 'pm10',
     'value': 3,
     'lastUpdated': '2020-01-03T12:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}},
    {'parameter': 'pm25',
     'value': 2.3,
     'lastUpdated': '2020-01-03T12:00:00.000Z',
     'unit': 'µg/m³',
     'sourceName': 'AirNow',
     'averagingPeriod': {'value': 1, 'unit': 'hours'}}],
   'coordinates': {'latitude': 45.468597, 'longitude': -98.494064}},
  {'location': 'Aberdeen-Division St',
   'city': 'Aberdeen',

In [7]:
# Extracting the data 'results'
data = pd.DataFrame(json_normalize(response.json()['results'])).reset_index()
data.shape
data.head()

,index,city,coordinates.latitude,coordinates.longitude,country,distance,location,measurements
0,0,CA8 - ARB,38.684364,-120.98818,US,8.648898e+06,1001,"[{'parameter': 'pm25', 'value': 13.9, 'lastUpd..."
1,1,CA8 - ARB,38.673860,-120.94338,US,8.648332e+06,1008,"[{'parameter': 'pm25', 'value': -4.2, 'lastUpd..."
2,2,Omaha-Council Bluffs,41.322470,-95.93799,US,7.317289e+06,16th and Whitmore,"[{'parameter': 'o3', 'value': 0.016, 'lastUpda..."
3,3,Farmington,36.809700,-107.65170,US,8.289569e+06,1NL Navajo Lake,"[{'parameter': 'o3', 'value': 0.024, 'lastUpda..."
4,4,Tucson,32.205000,-110.87720,US,8.880825e+06,22nd Street & Craycr,"[{'parameter': 'o3', 'value': 0.054, 'lastUpda..."

### Flattening the DataFrame

In [8]:
dic_flatten = [flatten(d) for d in response.json()['results']]
dic_flatten
data_flatten = pd.DataFrame(dic_flatten).reset_index()
data_flatten.head()
# # data.shape
# data.columns

# Create for loop to extract parameters individually?

,index,city,coordinates_latitude,coordinates_longitude,country,distance,location,measurements_0_averagingPeriod_unit,measurements_0_averagingPeriod_value,measurements_0_lastUpdated,...,measurements_4_sourceName,measurements_4_unit,measurements_4_value,measurements_5_averagingPeriod_unit,measurements_5_averagingPeriod_value,measurements_5_lastUpdated,measurements_5_parameter,measurements_5_sourceName,measurements_5_unit,measurements_5_value
0,0,CA8 - ARB,38.684364,-120.98818,US,8.648898e+06,1001,hours,1,2020-03-09T15:00:00.000Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,CA8 - ARB,38.673860,-120.94338,US,8.648332e+06,1008,hours,1,2020-03-09T17:00:00.000Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Omaha-Council Bluffs,41.322470,-95.93799,US,7.317289e+06,16th and Whitmore,hours,1,2017-11-01T11:00:00.000Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Farmington,36.809700,-107.65170,US,8.289569e+06,1NL Navajo Lake,hours,1,2017-01-13T15:00:00.000Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Tucson,32.205000,-110.87720,US,8.880825e+06,22nd Street & Craycr,hours,1,2020-03-30T20:00:00.000Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Trying to extract the parameters(sub dicts):

In [9]:
# First Try:

# len(data['measurements'])
# data['measurements'].apply(lambda x: json_normalize(dict(x)))

In [10]:
# Second Try:
data['measurements'][2]

# transformar em pd series
measurements = data['measurements'].apply(lambda x: pd.Series(x[0]))
measurements.head()

# Extracted only the first dictionary (parameter)

,parameter,value,lastUpdated,unit,sourceName,averagingPeriod
0,pm25,13.900,2020-03-09T15:00:00.000Z,µg/m³,AirNow,"{'value': 1, 'unit': 'hours'}"
1,pm25,-4.200,2020-03-09T17:00:00.000Z,µg/m³,AirNow,"{'value': 1, 'unit': 'hours'}"
2,o3,0.016,2017-11-01T11:00:00.000Z,ppm,AirNow,"{'value': 1, 'unit': 'hours'}"
3,o3,0.024,2017-01-13T15:00:00.000Z,ppm,AirNow,"{'value': 1, 'unit': 'hours'}"
4,o3,0.054,2020-03-30T20:00:00.000Z,ppm,AirNow,"{'value': 1, 'unit': 'hours'}"

In [11]:
# Merge tbales
# data.merge(measurements,  left_index=True,  right_index=True)
# drop measurements

## Requesting by  Measurements

### PM25

In [15]:
cities = ['Bombaim', 'Istambul', 'Londres', 'Bogotá','New York', 'Tóquio', 'São Paulo']
countries_response = ['China', 'India', 'Turkey', 'United Kingdom','Colombia', 'United States', 'Japan', 'Brazil']

In [38]:
# url = "https://api.openaq.org/v1/measurements?parameter=pm25&city=London&date_from=2019-03-01"
# response = requests.get(url)
# response
# response.json()

In [22]:
# pd.DataFrame(response.json())
data = pd.DataFrame(json_normalize(response.json()['results'])).reset_index()
data.head()
data.shape

(2000, 11)

In [36]:
# Fazer requests separadas e depois concat

# Criar um for loop pra request de todos os parâmetros?

# Criar logica para buscar só as infos das cidades que quero analisar?